### ISSUE TITLE
Deployment: Set up Let's Encrypt SSL cert

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#222]
After #197

**Comment by c-simpson** [comment]
I registered the **pawsdp.org** domain.

**Comment by dkelley** [comment]
Now that we are deployed to sandbox, I think we leave this alone for now. Can we move this to the backlog?  @c-simpson

**Comment by c-simpson** [comment]
Here's all it takes with the holo stuff   (release-values.yaml):

```
  tls:   

    - secretName: paws-data-pipeline-tls   
     
      hosts:   

        - paws-data-pipeline.sandbox.k8s.phl.io    
        
        - test.pawsdp.org
```


https://github.com/CodeForPhilly/cfp-sandbox-cluster/blob/5fefc9a3f39150ac1cdfce9129bfdc124db0afb3/paws-data-pipeline/release-values.yaml#L12-L16
